tables:
  fhv_tripdata:
    process:
      - calculations:
          duration_seconds: unix_timestamp(dropOff_datetime) - unix_timestamp(pickup_datetime)
      - refinement:
          drop_columns: [SR_Flag]
          filters:
            - "pickup_datetime <= dropOff_datetime"
  fhvhv_tripdata:
    process:
      - calculations:
          duration_seconds: unix_timestamp(dropOff_datetime) - unix_timestamp(pickup_datetime)
      - refinement:
          drop_columns: []
          filters:
            - "pickup_datetime <= dropOff_datetime"
  green_tripdata:
    process:
      - calculations:
          duration_seconds: unix_timestamp(lpep_dropoff_datetime) - unix_timestamp(lpep_pickup_datetime)
      - refinement:
          drop_columns: [ehail_fee]
          filters:
            - "year(lpep_pickup_datetime) between 2022 and 2026"
            - "lpep_pickup_datetime <= lpep_dropoff_datetime"
  yellow_tripdata:
    process:
      - calculations:
          duration_seconds: unix_timestamp(tpep_dropoff_datetime) - unix_timestamp(tpep_pickup_datetime)
      - refinement:
          drop_columns: []
          filters:
            - "year(tpep_pickup_datetime) between 2022 and 2026"
            - "tpep_pickup_datetime <= tpep_dropoff_datetime"
path:
  basePath: s3a://nyc-taxi/bronze/nyc/
  outputPath: s3a://nyc-taxi/silver/nyc