general:
  default_args:
    owner: 'bronze'
    retries: 5
    retry_delay: 5
  dag_configs:
    - dag_id: "bronze"
      dag_type: "nyc"
      schedule_interval: null
      max_active_runs: 1
      start_date: "2025-05-05"
      catchup: false
      is_paused_upon_creation: false
      tasks:
        - task_id: bronze
          script_path: "/opt/airflow/src/ingestion/bronze.py"