general:
  default_args:
    owner: 'zones'
    retries: 5
    retry_delay: 5
  dag_configs:
    - dag_id: "bronze_zones"
      dag_type: "zones"
      schedule_interval: null
      max_active_runs: 1
      start_date: "2025-05-05"
      catchup: false
      is_paused_upon_creation: false
      tasks:
        - task_id: zones
          script_path: "/opt/airflow/src/ingestion/zones.py"