version: 2

sources:
  - name: nyc_taxi
    schema: taxi
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
      - name: fhv_tripdata
      - name: fhvhv_tripdata
      - name: zones