select 
    cast(date_format(pickup_datetime, '%Y%m%d') as integer) as date_key,
    hvfhs_license_num,
    pickup_location_id,
    dropoff_location_id,
    dispatching_base_num,
    originating_base_num,
    request_datetime,
    on_scene_datetime,
    pickup_datetime,
    dropoff_datetime,
    duration_seconds,
    trip_miles,
    trip_time,
    base_passenger_fare,
    tolls,
    bcf as bcf_amount,
    sales_tax,
    congestion_surcharge,
    airport_fee,
    tips,
    driver_pay,
    (base_passenger_fare + tolls + bcf + sales_tax + congestion_surcharge + airport_fee + tips) as total_passenger_paid,
    case when shared_request_flag = 'Y' then true else false end as is_shared_requested,
    case when shared_match_flag   = 'Y' then true else false end as is_shared_matched,
    case when access_a_ride_flag  = 'Y' then true else false end as is_access_a_ride,
    case when wav_request_flag    = 'Y' then true else false end as is_wav_requested,
    case when wav_match_flag      = 'Y' then true else false end as is_wav_matched
from {{ ref('stg_fhvhv_tripdata') }}